version: "2"

services:
  tor:
     image: jsevans/aarch64-tor-hidden-service
     links:
          - db
     restart: always
# Keep keys in volumes
     volumes:
          - .tor:/var/lib/tor/hidden_service
     environment:
# Set mapping ports
         ETHERPAD_PORTS: "9001:9001"
        
  db:
     image: mariadb
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: rootpass
         MYSQL_DATABASE: etherpad
         MYSQL_USER: wordpress
         MYSQL_PASSWORD: wordpress123
     volumes:
          - .data:/var/lib/mysql
  etherpad:
      build: .
      depends_on:
          - db
      #image: tvelocity/etherpad-lite
      links:
          - db
      restart: always
      environment:
         ETHERPAD_DB_HOST: db
         ETHERPAD_DB_USER: root
         ETHERPAD_DB_PASSWORD: rootpass
         ETHERPAD_ADMIN_PASSWORD: admin
      ports:
          - 9001:9001
