version: "2"

services:
  tor:
     image: jsevans/tor-hidden-service:latest
     links:
          - mediawiki
     restart: always
# Keep keys in volumes
     volumes:
          - "~/.keys/:/var/lib/tor/hidden_service/"
     environment:
        # Set mapping ports
         MEDIAWIKI_PORTS: "80:80"
  db:
     image: mariadb
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: rootpass
         MYSQL_DATABASE: mediawiki
         MYSQL_USER: wikigod
         MYSQL_PASSWORD: wikipass123

  mediawiki:
     depends_on:
          - db
     image: synctree/mediawiki
     links:
          - db
     restart: always
     environment:
         MEDIAWIKI_DB_HOST: db:3306
         MEDIAWIKI_DB_USER: wikigod
         MEDIAWIKI_DB_PASSWORD: wikipass123
