version: "2"
services:
  tor:
     image: jsevans/tor-hidden-service:latest
     links:
          - nextcloud
     restart: always
# Keep keys in volumes
     volumes:
          - ./tor:/var/lib/tor/hidden_service
     environment:
# Set mapping ports
        NEXTCLOUD_PORTS: "80:80"
  db:
     image: mariadb
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: rootpass
         MYSQL_DATABASE: owncloud
         MYSQL_USER: cloudadmin
         MYSQL_PASSWORD: wordpress123
     volumes:
          - ./mysql:/var/lib/mysql

  nextcloud:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./nextcloud:/var/www/html
    restart: always
