version: "2"
services:
  tor:
     build: tor_build/
     links:
          - starwars
     restart: always
# Keep keys in volumes
     volumes:
          - .tor:/var/lib/tor/hidden_service
     environment:
# Set mapping ports
        STARWARS_PORTS: "1977:23"

  starwars:
     build: starwars_build/
     restart: always
