version: "2"

services:
  tor:
     build: tor_build/
     links:
          - ghost
     restart: always
# Keep keys in volumes
     volumes:
          - ".tor/:/var/lib/tor/hidden_service/"
     environment:
        # Set mapping ports
         GHOST_PORTS: "80:2368"

  ghost:
     build: ghost_build/
     restart: always
     ports:
             - 2368:2368

