version: "2"

services:
  tor:
     image: jsevans/docker-tor-hidden-service:latest
     links:
          - paperwork
     restart: always
     volumes:
          - ./keys/:/var/lib/tor/hidden_service/
     environment:
        # Set mapping ports
         PAPERWORK_PORTS: "80:80"

  paperwork:
     image: conoria/paperwork
     links:
          - paperwork-db:paperwork-db

  paperwork-db:
     image: mariadb
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: rootpass
         MYSQL_DATABASE: wordpress
         MYSQL_USER: wordpress
         MYSQL_PASSWORD: wordpress123
     volumes:
          - ./mysql:/var/lib/mysql

