version: "2"
services:
  tor:
     build: tor_build/
     links:
          - nyan
     restart: always
# Keep keys in volumes
     volumes:
          - ./tor:/var/lib/tor/hidden_service
     environment:
# Set mapping ports
        NYAN_PORTS: "23:23"

  nyan:
     build: nyan_build/
     restart: always
